/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import static applicationmanager.loginUI.LoggerInf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import logger.LoggerCode;
import logger.LoggerInterface;

/**
 *
 * @author 10122_000
 */
public final class managerUI extends javax.swing.JFrame {

    /**
     * Creates new form managerUI
     */
    public static LoggerInterface LoggerInf;
    public static JPopupMenu popupMenu;
    public static int currentRowIndex = 0;
    
    
    public managerUI() {
        initComponents();
        
         // create Logger instance
        LoggerInf = new LoggerInterface(this.getClass().getSimpleName());
        LoggerInf.SetLevel(true);
        
        // set dialog position
        centreWindow();
        
        // config table view
        configTableView();
    }
    
    public void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int height = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(width, height);
        LoggerInf.Log(LoggerCode.LOGGER_LEVEL_INFO, "managerdialog: centreWindow");
    }
    
    
    public void configTableView(){
        // config popup menu
        configPopupMenu();
       
        // sets the popup menu for the table
        tableView.setComponentPopupMenu(popupMenu);
    }
    
    public void configPopupMenu(){
        popupMenu = new JPopupMenu();
        
        // edit function
        JMenuItem menuItemEdit = new JMenuItem("Edit");
        menuItemEdit.addActionListener((ActionEvent e) -> {
            currentRowIndex = tableView.getSelectedRow();
            LoggerInf.Log(LoggerCode.LOGGER_LEVEL_INFO, "managerUI: add item " + currentRowIndex);
        });
        
        // remove function
        JMenuItem menuItemRemove = new JMenuItem("Remove");
        menuItemRemove.addActionListener((ActionEvent e) -> {
            currentRowIndex = tableView.getSelectedRow();
            LoggerInf.Log(LoggerCode.LOGGER_LEVEL_INFO, "managerUI: remove item " + currentRowIndex);
        });
        
        // remove-all function
        JMenuItem menuItemRemoveAll = new JMenuItem("Remove all");
        menuItemRemoveAll.addActionListener((ActionEvent e) -> {
            currentRowIndex = tableView.getSelectedRow();
            LoggerInf.Log(LoggerCode.LOGGER_LEVEL_INFO, "managerUI: remove all item " + currentRowIndex);
        });
        
        
        // add item into menu
        popupMenu.add(menuItemEdit);
        popupMenu.add(menuItemRemove);
        popupMenu.add(menuItemRemoveAll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("APPLICATION MANAGER MAIN SCREEN");

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "Nhuong Nguyen", "10-12-1992", "Ben Tre", "Univerity of Science"},
                {"002", "Thai Tran", "01-01-1990", "Thanh pho HCM", "Univeristy of Science"},
                {"003", "Kinh Tran", "12-02-1990", "Thanh pho HCM", "University of Science"},
                {"004", "Tung Nguyen", "15-10-1992", "Dong Thap", "University of Technology"},
                {"005", "Nguyen Tran", "25-08-1992", "Tien Giang", "Univerity of Science"}
            },
            new String [] {
                "id", "name", "date of birth", "address", "university"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setMinWidth(25);
            tableView.getColumnModel().getColumn(0).setMaxWidth(50);
            tableView.getColumnModel().getColumn(4).setMinWidth(200);
            tableView.getColumnModel().getColumn(4).setMaxWidth(250);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new managerUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableView;
    // End of variables declaration//GEN-END:variables
}
