/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import applicationmanager.loginUI;
import static applicationmanager.loginUI.LoggerInf;
import database.accountInterface;
import database.userManipulation;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logger.LoggerCode;
import singleton.signupCode;
import singleton.singletonUI;

/**
 *
 * @author 10122_000
 */
public final class signupUI extends javax.swing.JFrame {

    public static void getInstance() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form signupUI
     */
    public signupUI() {
        initComponents();
        
        // config dialog position
        centreWindow();
        
        // set component
        singletonUI.getInstance().setSignupInstance(this);
    }
    
    public void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int height = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(width, height);
        LoggerInf.Log(LoggerCode.LOGGER_LEVEL_INFO, "loginUI > centreWindow");
    }

    public int checkCreateAccountInformation(){
        String strUsername = txtSignupUsername.getText();
        String strPassword = txtsignupPassword.getText();
        String strRepassword = txtSignupRepassword.getText();
        
        int errorCode = -1;
        if (strUsername.isEmpty() == true){
            errorCode = signupCode.SIGNUP_ERROR_EMPTY_USERNAME;
        }else if (strPassword.isEmpty() == true){
            errorCode = signupCode.SIGNUP_ERROR_EMPTY_PASSWORD;
        }else if (strRepassword.isEmpty() == true){
            errorCode = signupCode.SIGNUP_ERROR_EMPTY_REPASSWORD;
        }else if (strPassword.equals(strRepassword) == false){
            errorCode = signupCode.SIGNUP_ERROR_MISMATCH_PASSWORD;
        }else if (strUsername.length() < signupCode.MINIMUM_LENGTH){
            errorCode = signupCode.SIGNUP_ERROR_TOO_SHORT_USERNAME;
        }else if (strPassword.length() < signupCode.MINIMUM_LENGTH){
            errorCode = signupCode.SIGNUP_ERROR_TOO_SHORT_PASSWORD;
        }else{
            errorCode = signupCode.SIGNUP_OK;
        }
        
        return errorCode;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSignupUsername = new javax.swing.JTextField();
        txtsignupPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSignupRepassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onDialogClose(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onDialogClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("APPLICATION MANAGER SIGNING UP SCRREN");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Username");

        txtSignupUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSignupUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtsignupPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtsignupPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Repassword");

        txtSignupRepassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSignupRepassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBack.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(13, 13, 13))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSignupUsername)
                                    .addComponent(txtsignupPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtSignupRepassword, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnBack)
                        .addGap(43, 43, 43)
                        .addComponent(btnCreate)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSignupUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsignupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSignupRepassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnCreate))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onDialogClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onDialogClose
        try{
            this.dispose();
            System.gc();
            singletonUI.getInstance().getLoginInstance().show();
        }catch (Exception ex){
            Logger.getLogger(signupUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onDialogClose

    private void onDialogClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onDialogClosing
        try{
            this.dispose();
            System.gc();
            singletonUI.getInstance().getLoginInstance().show();
        }catch (Exception ex){
            Logger.getLogger(signupUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onDialogClosing

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            // Return to login sreen
            this.dispose();
            System.gc();
            singletonUI.getInstance().getLoginInstance().show();
        } catch (Exception ex) {
            Logger.getLogger(signupUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        int errorCode = checkCreateAccountInformation();
        
        if (errorCode == signupCode.SIGNUP_OK){
            accountInterface newAccount = new accountInterface();
            newAccount.setStrUsername(txtSignupUsername.getText());
            newAccount.setStrPassword(txtsignupPassword.getText());
            
            boolean bChecker = false;
            try {
                bChecker = userManipulation.getUserManipulationInstance().InsertNewUserInformation(newAccount);
                 if (bChecker == true){
                    // create an new account
                    JOptionPane.showMessageDialog(null, "Create an account successfully!", 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                }else{
                     Logger.getLogger(signupUI.class.getName()).log(Level.SEVERE, null, "Create new account fail");
                 }
            } catch (SQLException ex) {
                Logger.getLogger(signupUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (newAccount!=null){
                newAccount = null;
            }
            System.gc();
        }else{
            switch(errorCode){
                case signupCode.SIGNUP_ERROR_EMPTY_USERNAME:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_EMPTY_USERNAME, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                    break;
                
                
                case signupCode.SIGNUP_ERROR_EMPTY_PASSWORD:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_EMPTY_PASSWORD, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);  
                    break;
                    
                case signupCode.SIGNUP_ERROR_EMPTY_REPASSWORD:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_EMPTY_REPASSWORD, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                    break;
                    
                case signupCode.SIGNUP_ERROR_MISMATCH_PASSWORD:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_MISMATCH_PASSWORD, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                    break;
                    
                case signupCode.SIGNUP_ERROR_TOO_SHORT_USERNAME:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_TOO_SHORT_USERNAME, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                    break;
                    
                case signupCode.SIGNUP_ERROR_TOO_SHORT_PASSWORD:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_TOO_SHORT_PASSWORD, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                    break;
                    
                default:
                    JOptionPane.showMessageDialog(null, signupCode.SIGNUP_STRING_UNKNOWN_CODE, 
                                    "Signup Application", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new signupUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtSignupRepassword;
    private javax.swing.JTextField txtSignupUsername;
    private javax.swing.JPasswordField txtsignupPassword;
    // End of variables declaration//GEN-END:variables
}
